/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlibanhang;


import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author My HP
 */
public class frmNhapHangAdd extends javax.swing.JFrame {

    
     private static String nhaCungCap;
     private String maNhapHang="";

    public String getMaNhapHang() {
        return maNhapHang;
    }

    public void setMaNhapHang(String maNhapHang) {
        this.maNhapHang = maNhapHang;
    }

    

   

    public static String getNhaCungCap() {
        return nhaCungCap;
    }

    public static void setNhaCungCap(String nhaCungCap) {
        frmNhapHangAdd.nhaCungCap = nhaCungCap;
    }
    

    

    

   
    
    /**
     * Creates new form frmNhapHangAdd
     */
    public frmNhapHangAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaNhapHang = new javax.swing.JTextField();
        txtNhaCungCap = new javax.swing.JTextField();
        dtNgayNhap = new com.toedter.calendar.JDateChooser();
        txtTongTienNhap = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThemHangHoa = new javax.swing.JButton();
        btnXoaHangHoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSuaThongTin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSuaSoLuong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhập hàng hóa"));

        jLabel3.setText("Mã nhập hàng:");

        jLabel5.setText("Nhà cung cấp (*):");

        jLabel6.setText("Ngày nhập:");

        jLabel7.setText("Tổng tiền nhập (*):");

        txtNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhaCungCapActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/stanford/j0622/qlsinhvien/images/save.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/com/stanford/j0622/qlsinhvien/images/cancel.gif"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnThemHangHoa.setText("Thêm hàng hóa");
        btnThemHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHangHoaActionPerformed(evt);
            }
        });

        btnXoaHangHoa.setText("Xóa hàng hóa");
        btnXoaHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHangHoaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sửa số lượng hàng hóa"));

        btnSuaThongTin.setText("Sửa thông tin");
        btnSuaThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThongTinActionPerformed(evt);
            }
        });

        jLabel1.setText("Nhập số lượng:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(btnSuaThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSuaSoLuong))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(txtSuaSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuaThongTin)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40)
                                .addComponent(txtMaNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5)
                                .addGap(25, 25, 25)
                                .addComponent(txtNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addComponent(txtTongTienNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemHangHoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoaHangHoa)
                            .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(dtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTongTienNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemHangHoa)
                            .addComponent(btnXoaHangHoa))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCapNhat)
                            .addComponent(btnDong)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      
        if(!maNhapHang.isEmpty())//TH sửa
        {
            this.setTitle("Sửa thông tin nhập hàng");
            
            //Hiển thị chi tiết sinh viên trước khi sửa
            hienThiChiTiet();
            hienThiDanhSachChiTiet();
        }
        else
        {
            this.setTitle("Thêm mới thông tin nhập hàng");
        }
    }//GEN-LAST:event_formWindowOpened

    public void thongTinChiTiet()
    {
        jPanel2.setVisible(false);
        btnThemHangHoa.setVisible(false);
        btnCapNhat.setVisible(false);
      
        btnXoaHangHoa.setVisible(false);
        
    }
     public static void hienThiDanhSachChiTiet()
    {
        //Khai báo 1 tiêu đề
        
        String colTieuDe[] = new String[]{"ID", "Tên hàng", "Số lượng", "Giá bán", "Tổng giá tiền"};
        
        //Khai báo đối tượng để thiển thị lên table
        DefaultTableModel model = new DefaultTableModel(colTieuDe, 0);
        String ID = txtMaNhapHang.getText();
        
        //Lấy danh sách sv
        List<ChiTietDonHangNhap> lstChiTietDonHangNhap = DataProvider.getChiTietDonHangNhapBus().layDanhSach(ID);
        
        Object row[] = null;
        
        //Duyệt để đưa vào model
        for(ChiTietDonHangNhap kh : lstChiTietDonHangNhap)
        {
            //Khởi tạo mảng
            row = new Object[5];
            
            row[0] = kh.getID();
            row[1] = kh.getTenHang();
            row[2] = kh.getSoLuong();
            row[3] = kh.getGiaTien();
            row[4] = kh.getTongGiaTien();
            
            //Thêm vào model
            model.addRow(row);
        }
        int tongTien=0;
        //Hiển thị lên table
        jTable1.setModel(model);     
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            int tien = (int) jTable1.getValueAt(i, 4);
            tongTien += tien;
        }
        txtTongTienNhap.setText(""+tongTien);
    }
    
     private void hienThiChiTiet()
    {
        NhapHang objNH = DataProvider.getNhapHangBus().layChiTietTheoMa(maNhapHang);
        
        if(objNH != null)
        {
            txtMaNhapHang.setText(maNhapHang);
            txtMaNhapHang.setEditable(false);
            
            txtTongTienNhap.setText(Integer.toString(objNH.getTongTienHang()));
            
            
          
           
            txtNhaCungCap.setText(objNH.getTenNhaCungCap());
          
           
            dtNgayNhap.setDate(objNH.getNgayNhap());
            
        }
        
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_formWindowActivated

   
    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        
        NhapHang objNH = new NhapHang();
        

        String maHang = "", tenHang = "", ghiChu = "", maNhap = "", trangThai = "",nhaCungCap="",strSoLuong="",strTongTienNhap="";

        int soLuong=0,tongTienNhap=0;
        

       
        nhaCungCap = txtNhaCungCap.getText();
        maNhap = txtMaNhapHang.getText();
       
        strTongTienNhap=txtTongTienNhap.getText();
        tongTienNhap=Integer.parseInt(strTongTienNhap);
        
        //Gán giá trị cho các thuộc tính
       
        if(nhaCungCap.trim().length() == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Bạn cần phải chọn nhà cung cấp ");
            
            return;
        }
        
       
       
        
        
        
        
            objNH.setMaNhap(maNhap);
        
        
      
        objNH.setNgayNhap(dtNgayNhap.getDate());
        objNH.setTenNhaCungCap(nhaCungCap);
        
      
        objNH.setTongTienHang(tongTienNhap);
                

        
        boolean ketQua = false;
         boolean ketQua1 = false;

        //Khai báo 1 đối tượng
        NhapHangBusiness sinhVienBus = new NhapHangBusiness();
        if(!maNhapHang.isEmpty())//TH sửa
        {
            
            ketQua = sinhVienBus.capNhat(objNH);
            

        }
        else
        {
            //Thực hiện thêm mới
             
            ketQua = sinhVienBus.themMoi(objNH);
           
        }

        if(ketQua)//true
        {
            JOptionPane.showMessageDialog(rootPane, "Thực hiện cập nhật nhập hàng thành công");
            //Reload lại danh sách
            GiaoDienChinh.hienThiDanhSachNhapHang();
        }

    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnThemHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHangHoaActionPerformed
        // TODO add your handling code here:
        frmChonHangHoa frmThem =new frmChonHangHoa();
        frmThem.setVisible(true);
        frmThem.setNhapHangOrXuatHang("NhapHang");
        String idDonHangNhap;
        idDonHangNhap=txtMaNhapHang.getText();
        frmThem.setIdDonHangNhap(idDonHangNhap);
    }//GEN-LAST:event_btnThemHangHoaActionPerformed

    private void btnSuaThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThongTinActionPerformed
        // TODO add your handling code here:
        int soLuong=0;
        soLuong=Integer.parseInt(txtSuaSoLuong.getText());
        ChiTietDonHangNhap objCT = new ChiTietDonHangNhap();
            

        String strGia="",ID="",strSoLuongCu="",tenHang="";
        
        int gia=0,tongGia=0,soLuongCu=0;
           
            
        
       
      int dongChon = 0;

        dongChon = jTable1.getSelectedRow();

        

        //Lấy mã sv của dòng chọn trên jtable
        strGia = "" + jTable1.getValueAt(dongChon, 3);
        tenHang = "" + jTable1.getValueAt(dongChon, 1);
        
        ID = "" + jTable1.getValueAt(dongChon, 0);
        strSoLuongCu = "" + jTable1.getValueAt(dongChon, 2);
        soLuongCu=Integer.parseInt(strSoLuongCu);
        gia=Integer.parseInt(strGia);

        
       
        tongGia=soLuong*gia;
       objCT.setID(ID);
        objCT.setSoLuong(soLuong);
        objCT.setTenHang(tenHang);
        objCT.setGiaTien(gia);
        objCT.setTongGiaTien(tongGia);
        boolean ketQua = false;

        //Khai báo 1 đối tượng
        ChiTietDonHangNhapBusiness sinhVienBus = new ChiTietDonHangNhapBusiness();

        
            //Thực hiện thêm mới
            ketQua = sinhVienBus.capNhat(objCT);
            sinhVienBus.capNhatTonKho(objCT,soLuongCu);
            if(ketQua)//true
        {
            JOptionPane.showMessageDialog(rootPane, "Thực hiện cập nhật hóa đơn thành công");
            //Reload lại danh sách
            frmNhapHangAdd.hienThiDanhSachChiTiet();
        }
        
        
        
        
        
    }//GEN-LAST:event_btnSuaThongTinActionPerformed

    private void btnXoaHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHangHoaActionPerformed
        // TODO add your handling code here:
        
        int ketQua = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa không ?",
            "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if(ketQua == JOptionPane.YES_OPTION)//True
        {
            int  dongChon = jTable1.getSelectedRow();

            String ID = "",tenHang="",strSoLuong="";
            int soLuong=0;

            //Lấy mã sv của dòng chọn trên jtable
            ID = "" + jTable1.getValueAt(dongChon, 0);
            tenHang = "" + jTable1.getValueAt(dongChon, 1);
             strSoLuong = "" + jTable1.getValueAt(dongChon, 2);
             soLuong=Integer.parseInt(strSoLuong);
            

            boolean kq = DataProvider.getChiTietDonHangNhapBus().xoa(ID);
            
            DataProvider.getChiTietDonHangNhapBus().xoaTonKho(tenHang, soLuong);

            if(kq)
            {
                //Reload lại ds
                hienThiDanhSachChiTiet();
            }
        }
    }//GEN-LAST:event_btnXoaHangHoaActionPerformed

    private void txtNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhaCungCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhaCungCapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhapHangAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhapHangAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhapHangAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhapHangAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNhapHangAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnSuaThongTin;
    private javax.swing.JButton btnThemHangHoa;
    private javax.swing.JButton btnXoaHangHoa;
    private com.toedter.calendar.JDateChooser dtNgayNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private static javax.swing.JTextField txtMaNhapHang;
    private static javax.swing.JTextField txtNhaCungCap;
    private javax.swing.JTextField txtSuaSoLuong;
    private static javax.swing.JTextField txtTongTienNhap;
    // End of variables declaration//GEN-END:variables
}
